version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - GEMINI_API_KEY=AIzaSyDsFvZrJYGMaV0FG4AeUbDePoVC0RRL8E4
    depends_on:
      - postgres
